name: Windows-CRD

on:
  workflow_dispatch:
    inputs:
      crd_command:
        description: 'Paste Full Chrome Remote Desktop Command'
        required: true

      pin:
        description: '6 Digit PIN'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Install Chrome Remote Desktop
      run: |
        choco install chrome-remote-desktop-host -y

    - name: Extract Code And Start CRD
      shell: powershell
      run: |
        $fullCommand = "${{ github.event.inputs.crd_command }}"
        $pin = "${{ github.event.inputs.pin }}"

        if ($fullCommand -match '--code="([^"]+)"') {
            $code = $matches[1]
        } else {
            Write-Error "CRD code not found!"
            exit 1
        }

        & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" `
        --code="$code" `
        --redirect-url="https://remotedesktop.google.com/_/oauthredirect" `
        --name=$Env:COMPUTERNAME `
        --pin="$pin"

    - name: Keep Alive
      run: |
        while ($true) {
          Start-Sleep -Seconds 60
        }
